### PR TITLE
Admin dashboard 2

### PR DESCRIPTION
**Pull request by Jialipeng8**
-added features for admin dashboard(see attached screenshot)
-added changepassword(see attached screenshot)
please kindly advice any suggestions

### CODE REVIEW

**Comment by Jialipeng8** [comment]
Screenshot 2024-09-28 at 2 28 24 pm

**Comment by Jialipeng8** [comment]
Screenshot 2024-09-28 at 3 11 56 pm

**Comment by HendrickGu** [comment]
don't change the js file/(ㄒoㄒ)/~~

**Pull request merged**
